version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pextest_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
      - ./ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
      - .:/app
    depends_on:
      - certbot
    restart: always

  certbot:
    # CHANGE THIS: Use a custom build for Certbot
    build:
      context: ./certbot # Point to the directory containing the Certbot Dockerfile
      dockerfile: Dockerfile # Specify the Dockerfile name inside that directory
    container_name: pextest_certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock # This is still essential for socket access
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --nginx; echo \"Certbot renewal complete. Reloading Nginx...\"; /usr/bin/docker exec pextest_nginx nginx -s reload; sleep 12h & wait $${!}; done;'"

volumes:
  certbot_www:
  certbot_conf: